### ISSUE TITLE
Logins not working on Overwolf?

### ISSUE THREAD

**Issue by cheat117** [artdevgame/shots-fired-support#14]
Tried to do "premium" subscriptions through overwolf and I get "not connected" errors. Additionally, splitgate seems unavailable which is the only reason I was looking to use this.

Please let me know if you need any more info!

**Comment by ministerofpanic** [comment]
Hey @cheat117 👋🏻 

Sorry for the late response. I need to get better at keeping an eye on this place.
We may have caught up in Discord by now, but to answer your post...

Splitgate isn't support in v4, although I will be adding support for it in v5, which I'm hoping to release before end of the year. Progress is going well, so it's likely.

"Not connected" errors are unusual, that is probably related to OBS. Recently I've become aware of an issue when trying to use `v5` of `obs-websocket`. When you install this tool, please make sure you're using the latest `v4` download (currently 4.9.1). If you're still having issues, let me know on here or in Discord and I'd be happy to help.

Since your post, I have disabled subscriptions for now, so there should be no problem accessing all functionality without cost. 🎉
